---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-system.ssl.pv
  labels:
    app: traefik
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/persistentvolumes/kube-system/ssl
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-system.ssl.pvc
  labels:
    app: traefik
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: kube-system.ssl.pv
